modified.files.includes[relevant][ai-hub-cell-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][ai-hub-cell-java-rule]=\
    apps/ai-hub-cell/**/*Test.java

relevant.rule.names=ai-hub-cell-java-rule

test.batch.names[relevant][ai-hub-cell-java-rule]=\
    modules-integration-postgresql163

testray.main.component.name=AI Hub Cell