{{- if .Values.enabled -}}
{{- $elasticsearch := .Values.search.elasticsearch | default dict -}}
{{- $opensearch := .Values.search.opensearch | default dict -}}
{{- $overlay := .Values.overlay | default dict -}}
{{- $storage := .Values.storage | default dict -}}
apiVersion: aws.liferay.com/v1alpha1
kind: LiferayInfrastructure
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: "-20"
    name: {{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
spec:
    backup: {{ .Values.backup | toYaml | nindent 8 }}
    commonTags:
        EnvironmentId: {{ .Values.environmentId }}
        ProjectId: {{ .Values.projectId }}
    database: {{ .Values.database | toYaml | nindent 8 }}
    deletionProtection: {{ .Values.deletionProtection | default false }}
    environmentId: {{ .Values.environmentId }}
    overlay:
        region: {{ $overlay.region | default "us-west-2" | quote }}
    projectId: {{ .Values.projectId }}
    search: {{ .Values.search | toYaml | nindent 8 }}
    storage: {{ .Values.storage | toYaml | nindent 8 }}
{{- end -}}