apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    labels:
        component: backup-create-platform
    name: backup-create-cluster-role
rules:
    -   apiGroups: ["argoproj.io"]
        resources: ["workflowtaskresults"]
        verbs:
            -   create
            -   patch
    -   apiGroups: ["backup.liferay.cloud"]
        resources: ["liferaybackups"]
        verbs:
            -   create
            -   get
            -   list
            -   watch
    -   apiGroups: ["gcp.liferay.com"]
        resources: ["liferayinfrastructures"]
        verbs:
            -   get
            -   list