resource "kubernetes_manifest" "envoy_proxy_config" {
	manifest={
		apiVersion="gateway.envoyproxy.io/v1alpha1"
		kind="EnvoyProxy"
		metadata={
			name=local.gateway_proxy_config_name
			namespace=var.gateway_namespace
		}
		spec={
			provider={
				kubernetes={
					envoyDeployment={
						pod={
							annotations={
								"eks.amazonaws.com/role-arn"=data.aws_iam_role.envoy_proxy_role.arn
							}
							topologySpreadConstraints=[
								{
									labelSelector={
										matchLabels={
											"app.kubernetes.io/name"="envoy"
										}
									}
									maxSkew=1
									topologyKey="kubernetes.io/hostname"
									whenUnsatisfiable="ScheduleAnyway"
								}
							]
						}
						replicas=3
					}
					envoyHpa={
						maxReplicas=10
						metrics=[
							{
								resource={
									name="cpu"
									target={
										averageUtilization=75
										type="Utilization"
									}
								}
								type="Resource"
							}
						]
						minReplicas=3
					}
					envoyService={
						annotations={
							"service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags"="DeploymentName=${var.deployment_name}"
							"service.beta.kubernetes.io/aws-load-balancer-attributes"="load_balancing.cross_zone.enabled=true"
							"service.beta.kubernetes.io/aws-load-balancer-healthcheck-path"="/ready"
							"service.beta.kubernetes.io/aws-load-balancer-healthcheck-port"="19003"
							"service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol"="HTTP"
							"service.beta.kubernetes.io/aws-load-balancer-nlb-target-type"="ip"
							"service.beta.kubernetes.io/aws-load-balancer-proxy-protocol"="*"
							"service.beta.kubernetes.io/aws-load-balancer-scheme"=var.demo_mode ? "internet-facing" : "internal"
							"service.beta.kubernetes.io/aws-load-balancer-target-group-attributes"="proxy_protocol_v2.enabled=true"
							"service.beta.kubernetes.io/aws-load-balancer-type"="external"
						}
						externalTrafficPolicy="Local"
						type="LoadBalancer"
					}
				}
				type="Kubernetes"
			}
		}
	}
}
resource "kubernetes_manifest" "liferay_gateway_class" {
	manifest={
		apiVersion="gateway.networking.k8s.io/v1"
		kind="GatewayClass"
		metadata={
			name=var.gateway_class_name
		}
		spec={
			controllerName="gateway.envoyproxy.io/gatewayclass-controller"
			parametersRef={
				group="gateway.envoyproxy.io"
				kind="EnvoyProxy"
				name=local.gateway_proxy_config_name
				namespace=var.gateway_namespace
			}
		}
	}
}