{{- include "liferay-platform.operatorApplication" (list . (merge (dict
    "name" "eck-operator"
    "namespaceLabels" (dict "pod-security.kubernetes.io/enforce" "restricted")
    "syncWave" "-100") .Values.operatorApplications.eckOperator)) }}