apiDir: ../osb-faro-rest-api/src/main/java
apiPackagePath: com.liferay.osb.faro.rest
application:
    baseURI: /faro-rest
    className: FaroRestApplication
    name: Liferay.Faro.Rest
author: Leslie Wong
clientDir: ../osb-faro-rest-client/src/main/java
clientMavenGroupId: com.liferay
compatibilityVersion: 15
forcePredictableOperationId: true
forcePredictableSchemaName: true
generateBatch: false
javaEEPackage: jakarta
testDir: ../osb-faro-rest-test/src/testIntegration/java