{{- if .Values.createClusterResources -}}
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
    labels:
        {{- include "liferayAWSBackupRestore.labels" . | nindent 8 }}
    name: {{ include "liferayAWSBackupRestore.name" . }}
spec:
    arguments:
        parameters:
            -   name: recovery-point-arn
    artifactGC:
        {{- .Values.argo.workflowSpec.artifactGC | toYaml | nindent 8 }}
    artifactRepositoryRef:
        configMap: {{ include "liferayAWSBackupRestore.artifactRepositoryConfigMapName" . }}
    entrypoint: main
    podGC:
        {{- .Values.argo.workflowSpec.podGC | toYaml | nindent 8 }}
    templates:
        -   inputs:
                artifacts:
                    -   name: git-repository
                    -   name: infrastructure-values
                parameters:
                    -   name: commit-message
            name: apply-infra-changes
            steps:
                -   -   arguments:
                            artifacts:
                                -   from: "{{ "{{" }}inputs.artifacts.git-repository}}"
                                    name: git-repository
                        name: git-pull
                        template: git-pull
                -   -   arguments:
                            artifacts:
                                -   from: "{{ "{{" }}steps.git-pull.outputs.artifacts.git-repository}}"
                                    name: git-repository
                                -   from: "{{ "{{" }}inputs.artifacts.infrastructure-values}}"
                                    name: infrastructure-values
                        name: write-infra-values
                        template: write-infra-values
                -   -   arguments:
                            artifacts:
                                -   from: "{{ "{{" }}steps.write-infra-values.outputs.artifacts.git-repository}}"
                                    name: git-repository
                            parameters:
                                -   name: commit-message
                                    value: "{{ "{{" }}inputs.parameters.commit-message}}"
                        name: git-push
                        template: git-push
                -   -   name: argocd-sync
                        template: argocd-sync
                -   -   name: wait-observed-generation
                        template: wait-observed-generation
                -   -   name: argocd-wait
                        template: argocd-wait
        -   container:
                args:
                    -   app
                    -   sync
                    -   "{{ default (printf "%s-%s-infra" .Values.global.projectId .Values.global.environmentId) .Values.argoCD.infrastructureApplicationName }}"
                    -   --core
                    -   --timeout
                    -   "300"
                command: [argocd]
                image: "{{ .Values.images.argocd.repository }}:{{ .Values.images.argocd.tag }}"
                resources:
                    {{- .Values.resources.default | toYaml | nindent 20 }}
            name: argocd-sync
        -   container:
                args:
                    -   app
                    -   wait
                    -   "{{ default (printf "%s-%s-infra" .Values.global.projectId .Values.global.environmentId) .Values.argoCD.infrastructureApplicationName }}"
                    -   --core
                    -   --health
                    -   --timeout
                    -   "{{ .Values.argoCD.appWaitTimeoutSeconds }}"
                command: [argocd]
                image: "{{ .Values.images.argocd.repository }}:{{ .Values.images.argocd.tag }}"
                resources:
                    {{- .Values.resources.default | toYaml | nindent 20 }}
            name: argocd-wait
        -   name: checkout-git-repository
            outputs:
                artifacts:
                    -   name: git-repository
                        path: /src
            script:
                command: [sh]
                image: "{{ .Values.images.git.repository }}:{{ .Values.images.git.tag }}"
                resources:
                    {{- .Values.resources.default | toYaml | nindent 20 }}
                source: |-
                    {{- include "liferayAWSBackupRestore.script.gitCheckout" . | nindent 20 }}
                {{- include "liferayAWSBackupRestore.gitCredentials.volumeMount" . | nindent 16 }}
        -   container:
                args:
                    -   "s3"
                    -   "rm"
                    -   "s3://{{ "{{" }}inputs.parameters.s3-bucket-id}}/"
                    -   "--only-show-errors"
                    -   "--recursive"
                command: ["aws"]
                image: "{{ .Values.images.awsCli.repository }}:{{ .Values.images.awsCli.tag }}"
                resources:
                    {{- .Values.resources.default | toYaml | nindent 20 }}
            inputs:
                parameters:
                    -   name: s3-bucket-id
            name: clean-up-s3-bucket
        -   inputs:
                artifacts:
                    -   name: git-repository
                        path: /src
            name: get-current-infrastructure-state
            outputs:
                parameters:
                    -   name: data-active
                        valueFrom:
                            path: /tmp/data-active.txt
                    -   name: data-inactive
                        valueFrom:
                            path: /tmp/data-inactive.txt
                    -   name: s3-bucket-id-active
                        valueFrom:
                            path: /tmp/s3-bucket-id-active.txt
                    -   name: s3-bucket-id-inactive
                        valueFrom:
                            path: /tmp/s3-bucket-id-inactive.txt
            script:
                command: [sh]
                image: "{{ .Values.images.helmKubectl.repository }}:{{ .Values.images.helmKubectl.tag }}"
                resources:
                    {{- .Values.resources.default | toYaml | nindent 20 }}
                source: |-
                    {{- include "liferayAWSBackupRestore.script.getCurrentInfrastructureState" . | nindent 20 }}
        -   name: get-peer-recovery-points
            outputs:
                parameters:
                    -   name: rds-snapshot-id
                        valueFrom:
                            path: /tmp/rds-snapshot-id.txt
                    -   name: s3-recovery-point-arn
                        valueFrom:
                            path: /tmp/s3-recovery-point-arn.txt
            script:
                command: [sh]
                image: "{{ .Values.images.awsCli.repository }}:{{ .Values.images.awsCli.tag }}"
                resources:
                    {{- .Values.resources.default | toYaml | nindent 20 }}
                source: |-
                    {{- include "liferayAWSBackupRestore.script.getPeerRecoveryPoints" . | nindent 20 }}
        -   inputs:
                artifacts:
                    -   name: git-repository
                        path: /src
            name: git-pull
            outputs:
                artifacts:
                    -   name: git-repository
                        path: /src
            script:
                command: [sh]
                image: "{{ .Values.images.git.repository }}:{{ .Values.images.git.tag }}"
                resources:
                    {{- .Values.resources.default | toYaml | nindent 20 }}
                source: |-
                    {{- include "liferayAWSBackupRestore.script.gitPull" . | nindent 20 }}
                {{- include "liferayAWSBackupRestore.gitCredentials.volumeMount" . | nindent 16 }}
                workingDir: /src
        -   inputs:
                artifacts:
                    -   name: git-repository
                        path: /src
                parameters:
                    -   name: commit-message
            name: git-push
            script:
                command: [sh]
                image: "{{ .Values.images.git.repository }}:{{ .Values.images.git.tag }}"
                resources:
                    {{- .Values.resources.default | toYaml | nindent 20 }}
                source: |-
                    {{- include "liferayAWSBackupRestore.script.gitPush" . | nindent 20 }}
                {{- include "liferayAWSBackupRestore.gitCredentials.volumeMount" . | nindent 16 }}
                workingDir: /src
        -   container:
                args:
                    -   rollout
                    -   restart
                    -   statefulset
                    -   "{{ .Values.liferayWorkload.name }}"
                command: [kubectl]
                image: "{{ .Values.images.helmKubectl.repository }}:{{ .Values.images.helmKubectl.tag }}"
                resources:
                    {{- .Values.resources.default | toYaml | nindent 20 }}
            name: kubectl-rollout-restart
        -   container:
                args:
                    -   rollout
                    -   status
                    -   statefulset
                    -   "{{ .Values.liferayWorkload.name }}"
                    -   --timeout={{ .Values.liferayWorkload.rolloutTimeout }}
                command: [kubectl]
                image: "{{ .Values.images.helmKubectl.repository }}:{{ .Values.images.helmKubectl.tag }}"
                resources:
                    {{- .Values.resources.default | toYaml | nindent 20 }}
            name: kubectl-rollout-status
        -   dag:
                tasks:
                    -   name: checkout-git-repository
                        template: checkout-git-repository
                    -   arguments:
                            artifacts:
                                -   from: "{{ "{{" }}tasks.checkout-git-repository.outputs.artifacts.git-repository}}"
                                    name: git-repository
                                -   name: infrastructure-values
                                    raw:
                                        data: |-
                                            activeDataPlane: {{ "{{" }}tasks.get-current-infrastructure-state.outputs.parameters.data-inactive}}
                                            database:
                                                isRestoring: false
                            parameters:
                                -   name: commit-message
                                    value: Clean up inactive RDS instance
                        depends: restart-liferay
                        name: clean-up-rds-instance
                        template: apply-infra-changes
                    -   arguments:
                            parameters:
                                -   name: s3-bucket-id
                                    value: "{{ "{{" }}tasks.get-current-infrastructure-state.outputs.parameters.s3-bucket-id-active}}"
                        depends: restart-liferay
                        name: clean-up-s3-bucket
                        template: clean-up-s3-bucket
                    -   arguments:
                            artifacts:
                                -   from: "{{ "{{" }}tasks.checkout-git-repository.outputs.artifacts.git-repository}}"
                                    name: git-repository
                        depends: checkout-git-repository
                        name: get-current-infrastructure-state
                        template: get-current-infrastructure-state
                    -   name: get-peer-recovery-points
                        template: get-peer-recovery-points
                    -   depends: update-kubernetes-secret
                        name: restart-liferay
                        template: restart-liferay
                    -   arguments:
                            artifacts:
                                -   from: "{{ "{{" }}tasks.checkout-git-repository.outputs.artifacts.git-repository}}"
                                    name: git-repository
                                -   name: infrastructure-values
                                    raw:
                                        data: |-
                                            activeDataPlane: {{ "{{" }}tasks.get-current-infrastructure-state.outputs.parameters.data-active}}
                                            database:
                                                isRestoring: true
                                                snapshotIdentifier: {{ "{{" }}tasks.get-peer-recovery-points.outputs.parameters.rds-snapshot-id}}
                            parameters:
                                -   name: commit-message
                                    value: Provision inactive RDS instance from database snapshot identifier
                        depends: get-current-infrastructure-state && get-peer-recovery-points
                        name: restore-rds-instance
                        template: apply-infra-changes
                    -   arguments:
                            parameters:
                                -   name: s3-recovery-point-arn
                                    value: "{{ "{{" }}tasks.get-peer-recovery-points.outputs.parameters.s3-recovery-point-arn}}"
                                -   name: s3-bucket-id
                                    value: "{{ "{{" }}tasks.get-current-infrastructure-state.outputs.parameters.s3-bucket-id-inactive}}"
                        depends: get-current-infrastructure-state && get-peer-recovery-points
                        name: restore-s3-bucket
                        template: restore-s3-bucket
                    -   arguments:
                            artifacts:
                                -   from: "{{ "{{" }}tasks.checkout-git-repository.outputs.artifacts.git-repository}}"
                                    name: git-repository
                                -   name: infrastructure-values
                                    raw:
                                        data: |-
                                            activeDataPlane: {{ "{{" }}tasks.get-current-infrastructure-state.outputs.parameters.data-active}}
                                            database:
                                                isRestoring: false
                            parameters:
                                -   name: commit-message
                                    value: Roll back RDS instance
                        depends: "!restore-rds-instance.Skipped && !update-kubernetes-secret.Succeeded"
                        name: roll-back-rds-instance
                        template: apply-infra-changes
                    -   arguments:
                            parameters:
                                -   name: s3-bucket-id
                                    value: "{{ "{{" }}tasks.get-current-infrastructure-state.outputs.parameters.s3-bucket-id-inactive}}"
                        depends: "!restore-s3-bucket.Skipped && !update-kubernetes-secret.Succeeded"
                        name: roll-back-s3-bucket
                        template: clean-up-s3-bucket
                    -   arguments:
                            artifacts:
                                -   from: "{{ "{{" }}tasks.checkout-git-repository.outputs.artifacts.git-repository}}"
                                    name: git-repository
                                -   name: infrastructure-values
                                    raw:
                                        data: |-
                                            activeDataPlane: {{ "{{" }}tasks.get-current-infrastructure-state.outputs.parameters.data-inactive}}
                                            database:
                                                isRestoring: true
                                                snapshotIdentifier: null
                            parameters:
                                -   name: commit-message
                                    value: Update Liferay configuration to restored data plane
                        depends: restore-rds-instance && restore-s3-bucket
                        name: update-kubernetes-secret
                        template: apply-infra-changes
            name: main
        -   inputs:
                parameters:
                    -   name: s3-bucket-id
                    -   name: s3-recovery-point-arn
            name: restore-s3-bucket
            script:
                command: [sh]
                image: "{{ .Values.images.awsCli.repository }}:{{ .Values.images.awsCli.tag }}"
                resources:
                    {{- .Values.resources.default | toYaml | nindent 20 }}
                source: |-
                    {{- include "liferayAWSBackupRestore.script.restoreS3Bucket" . | nindent 20 }}
        -   name: restart-liferay
            steps:
                -   -   name: kubectl-rollout-restart
                        template: kubectl-rollout-restart
                -   -   name: kubectl-rollout-status
                        template: kubectl-rollout-status
        -   name: wait-observed-generation
            script:
                command: [sh]
                image: "{{ .Values.images.helmKubectl.repository }}:{{ .Values.images.helmKubectl.tag }}"
                resources:
                    {{- .Values.resources.default | toYaml | nindent 20 }}
                source: |-
                    {{- include "liferayAWSBackupRestore.script.waitObservedGeneration" . | nindent 20 }}
        -   container:
                args:
                    -   --indent
                    -   "4"
                    -   --inplace
                    -   ". *= load(\"/tmp/infrastructure-values.yaml\") | del(.. | select(. == null))"
                    -   "{{ default (printf "liferay/projects/%s/environments/%s/liferay.yaml" .Values.global.projectId .Values.global.environmentId) .Values.git.infrastructureRepository.paths.infrastructureValues }}"
                command: [yq]
                image: "{{ .Values.images.yq.repository }}:{{ .Values.images.yq.tag }}"
                resources:
                    {{- .Values.resources.default | toYaml | nindent 20 }}
                workingDir:
                    /src
            inputs:
                artifacts:
                    -   name: git-repository
                        path: /src
                    -   name: infrastructure-values
                        path: /tmp/infrastructure-values.yaml
            name: write-infra-values
            outputs:
                artifacts:
                    -   name: git-repository
                        path: /src
    ttlStrategy:
        {{- .Values.argo.workflowSpec.ttlStrategy | toYaml | nindent 8 }}
    volumes:
        -   name: git-credentials
            secret:
                secretName: {{ include "liferayAWSBackupRestore.gitCredentials.externalSecretName" . }}
{{- end -}}