{{- $parsedUrl := .Values.git.repository.url | urlParse -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    labels:
    {{- include "liferayAWSBackupRestore.labels" . | nindent 8 }}
    name: {{ include "liferayAWSBackupRestore.gitCredentials.externalSecretName" . }}
spec:
    data:
    -   remoteRef:
            key: {{ .Values.git.externalSecret.name }}
            property: {{ .Values.git.externalSecret.keys.username }}
        secretKey: username
    -   remoteRef:
            key: {{ .Values.git.externalSecret.name }}
            property: {{ .Values.git.externalSecret.keys.token }}
        secretKey: token
    refreshInterval: 1h
    secretStoreRef:
        kind: ClusterSecretStore
        name: {{ .Values.clusterSecretStoreName }}
    target:
        template:
            data:
                .git-credentials: |-
                    https://{{ "{{ .username }}" }}:{{ "{{ .token }}" }}@{{ $parsedUrl.host }}