argo:
    workflowSpec:
        artifactGC:
            strategy: OnWorkflowDeletion
        podGC:
            strategy: OnWorkflowSuccess
        ttlStrategy:
            secondsAfterCompletion: 86400
argoCD:
    appWaitTimeoutSeconds: 3600
    infrastructureApplicationName: ""
awsBackupService:
    restoreWaitTimeoutSeconds: 7200
createClusterResources: true
fullnameOverride: ""
git:
    externalSecret:
        keys:
            token: git_token
            username: git_username
        name: liferay/credentials/backup-restore-git-credentials
    infrastructureRepository:
        branch: master
        paths:
            infrastructureValues: ""
    user:
        emailAddress: ""
        name: ""
images:
    argocd:
        repository: argoproj/argocd
        tag: v2.12.2
    awsCli:
        repository: amazon/aws-cli
        tag: 2.27.63
    git:
        repository: alpine/git
        tag: 2.52.0
    helmKubectl:
        repository: dtzar/helm-kubectl
        tag: 4.1.1
    yq:
        repository: mikefarah/yq
        tag: 4.52.4
liferayWorkload:
    name: liferay-default
    rolloutTimeout: 15m
nameOverride: ""
resources:
    default:
        limits:
            cpu: 250m
            memory: 256Mi
        requests:
            cpu: 100m
            memory: 128Mi