/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.layout.page.template.model.impl;

import com.liferay.layout.page.template.model.LayoutPageTemplateStructureRelElementVariationAudienceEntryRel;
import com.liferay.layout.page.template.service.LayoutPageTemplateStructureRelElementVariationAudienceEntryRelLocalServiceUtil;

/**
 * The extended model base implementation for the LayoutPageTemplateStructureRelElementVariationAudienceEntryRel service. Represents a row in the &quot;LPTSREVAudienceEntryRel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LayoutPageTemplateStructureRelElementVariationAudienceEntryRelImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LayoutPageTemplateStructureRelElementVariationAudienceEntryRelImpl
 * @see LayoutPageTemplateStructureRelElementVariationAudienceEntryRel
 * @generated
 */
public abstract class
	LayoutPageTemplateStructureRelElementVariationAudienceEntryRelBaseImpl
		extends LayoutPageTemplateStructureRelElementVariationAudienceEntryRelModelImpl
		implements LayoutPageTemplateStructureRelElementVariationAudienceEntryRel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a layout page template structure rel element variation audience entry rel model instance should use the <code>LayoutPageTemplateStructureRelElementVariationAudienceEntryRel</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			LayoutPageTemplateStructureRelElementVariationAudienceEntryRelLocalServiceUtil.
				addLayoutPageTemplateStructureRelElementVariationAudienceEntryRel(
					this);
		}
		else {
			LayoutPageTemplateStructureRelElementVariationAudienceEntryRelLocalServiceUtil.
				updateLayoutPageTemplateStructureRelElementVariationAudienceEntryRel(
					this);
		}
	}

}
// LIFERAY-SERVICE-BUILDER-HASH:-160367178