modified.files.includes[relevant][design-library-web-playwright-rule]=**

playwright.projects.includes[playwright-js-tomcat101-postgresql163][relevant][design-library-web-playwright-rule]=\
    design-library-web.main

relevant.rule.names=design-library-web-playwright-rule

test.batch.names[relevant][design-library-web-playwright-rule]=\
    playwright-js-tomcat101-postgresql163