backup:
    enabled: false
    planName: liferay-backup
    region: us-west-2
    rules:
        -   retentionDays: 30
            ruleName: daily-backups
            schedule: cron(0 5 * * ? *)
            startWindow: 60
    selectionName: by-tags
    serviceRoleName: liferay-backup-restore
    vaultName: liferay-backup
enabled: true