{{- if .Values.backup.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
    labels:
        component: backup-create-platform
    name: backup-create-workflow-template
    namespace: {{ .Release.Namespace }}
spec:
    entrypoint: main
    podGC:
        strategy: OnWorkflowSuccess
    serviceAccountName: backup-create-service-account
    templates:
        -   name: main
            steps:
                -   -   name: create-backup
                        templateRef:
                            clusterScope: true
                            name: backup-create-cluster-workflow-template
                            template: main
    ttlStrategy:
        secondsAfterCompletion: 86400
{{- end -}}