{{- if .Values.enabled -}}
{{- $interval := .Values.podMonitoring.interval -}}
{{- range $name, $instance := .Values.podMonitoring.instances }}
---
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
    name: {{ $name }}
    namespace: {{ $.Release.Namespace }}
spec:
    endpoints:
        -   interval: {{ $interval }}
            {{- with $instance.metricRelabeling }}
            metricRelabeling:
            {{- range . }}
                -   action: {{ .action }}
                    regex: {{ .regex | quote }}
                    sourceLabels:
                    {{- range .sourceLabels }}
                        -   {{ . }}
                    {{- end }}
            {{- end }}
            {{- end }}
            {{- with $instance.path }}
            path: {{ . }}
            {{- end }}
            port: {{ $instance.port }}
    selector:
        matchLabels:
            {{- range $k, $v := $instance.matchLabels }}
            {{ $k }}: {{ $v | quote }}
            {{- end }}
{{- end }}
{{- end -}}