/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.commerce.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ExternalReferenceCodeModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the CommerceOrderAttachment service. Represents a row in the &quot;CommerceOrderAttachment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.commerce.model.impl.CommerceOrderAttachmentModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.commerce.model.impl.CommerceOrderAttachmentImpl</code>.
 * </p>
 *
 * @author Alessio Antonio Rendina
 * @see CommerceOrderAttachment
 * @generated
 */
@ProviderType
public interface CommerceOrderAttachmentModel
	extends BaseModel<CommerceOrderAttachment>, ExternalReferenceCodeModel,
			GroupedModel, MVCCModel, ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a commerce order attachment model instance should use the {@link CommerceOrderAttachment} interface instead.
	 */

	/**
	 * Returns the primary key of this commerce order attachment.
	 *
	 * @return the primary key of this commerce order attachment
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this commerce order attachment.
	 *
	 * @param primaryKey the primary key of this commerce order attachment
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this commerce order attachment.
	 *
	 * @return the mvcc version of this commerce order attachment
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this commerce order attachment.
	 *
	 * @param mvccVersion the mvcc version of this commerce order attachment
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the uuid of this commerce order attachment.
	 *
	 * @return the uuid of this commerce order attachment
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this commerce order attachment.
	 *
	 * @param uuid the uuid of this commerce order attachment
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the external reference code of this commerce order attachment.
	 *
	 * @return the external reference code of this commerce order attachment
	 */
	@AutoEscape
	@Override
	public String getExternalReferenceCode();

	/**
	 * Sets the external reference code of this commerce order attachment.
	 *
	 * @param externalReferenceCode the external reference code of this commerce order attachment
	 */
	@Override
	public void setExternalReferenceCode(String externalReferenceCode);

	/**
	 * Returns the commerce order attachment ID of this commerce order attachment.
	 *
	 * @return the commerce order attachment ID of this commerce order attachment
	 */
	public long getCommerceOrderAttachmentId();

	/**
	 * Sets the commerce order attachment ID of this commerce order attachment.
	 *
	 * @param commerceOrderAttachmentId the commerce order attachment ID of this commerce order attachment
	 */
	public void setCommerceOrderAttachmentId(long commerceOrderAttachmentId);

	/**
	 * Returns the group ID of this commerce order attachment.
	 *
	 * @return the group ID of this commerce order attachment
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this commerce order attachment.
	 *
	 * @param groupId the group ID of this commerce order attachment
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this commerce order attachment.
	 *
	 * @return the company ID of this commerce order attachment
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this commerce order attachment.
	 *
	 * @param companyId the company ID of this commerce order attachment
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this commerce order attachment.
	 *
	 * @return the user ID of this commerce order attachment
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this commerce order attachment.
	 *
	 * @param userId the user ID of this commerce order attachment
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this commerce order attachment.
	 *
	 * @return the user uuid of this commerce order attachment
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this commerce order attachment.
	 *
	 * @param userUuid the user uuid of this commerce order attachment
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this commerce order attachment.
	 *
	 * @return the user name of this commerce order attachment
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this commerce order attachment.
	 *
	 * @param userName the user name of this commerce order attachment
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this commerce order attachment.
	 *
	 * @return the create date of this commerce order attachment
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this commerce order attachment.
	 *
	 * @param createDate the create date of this commerce order attachment
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this commerce order attachment.
	 *
	 * @return the modified date of this commerce order attachment
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this commerce order attachment.
	 *
	 * @param modifiedDate the modified date of this commerce order attachment
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the commerce order ID of this commerce order attachment.
	 *
	 * @return the commerce order ID of this commerce order attachment
	 */
	public long getCommerceOrderId();

	/**
	 * Sets the commerce order ID of this commerce order attachment.
	 *
	 * @param commerceOrderId the commerce order ID of this commerce order attachment
	 */
	public void setCommerceOrderId(long commerceOrderId);

	/**
	 * Returns the file entry ID of this commerce order attachment.
	 *
	 * @return the file entry ID of this commerce order attachment
	 */
	public long getFileEntryId();

	/**
	 * Sets the file entry ID of this commerce order attachment.
	 *
	 * @param fileEntryId the file entry ID of this commerce order attachment
	 */
	public void setFileEntryId(long fileEntryId);

	/**
	 * Returns the priority of this commerce order attachment.
	 *
	 * @return the priority of this commerce order attachment
	 */
	public double getPriority();

	/**
	 * Sets the priority of this commerce order attachment.
	 *
	 * @param priority the priority of this commerce order attachment
	 */
	public void setPriority(double priority);

	/**
	 * Returns the restricted of this commerce order attachment.
	 *
	 * @return the restricted of this commerce order attachment
	 */
	public boolean getRestricted();

	/**
	 * Returns <code>true</code> if this commerce order attachment is restricted.
	 *
	 * @return <code>true</code> if this commerce order attachment is restricted; <code>false</code> otherwise
	 */
	public boolean isRestricted();

	/**
	 * Sets whether this commerce order attachment is restricted.
	 *
	 * @param restricted the restricted of this commerce order attachment
	 */
	public void setRestricted(boolean restricted);

	/**
	 * Returns the title of this commerce order attachment.
	 *
	 * @return the title of this commerce order attachment
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this commerce order attachment.
	 *
	 * @param title the title of this commerce order attachment
	 */
	public void setTitle(String title);

	/**
	 * Returns the type of this commerce order attachment.
	 *
	 * @return the type of this commerce order attachment
	 */
	@AutoEscape
	public String getType();

	/**
	 * Sets the type of this commerce order attachment.
	 *
	 * @param type the type of this commerce order attachment
	 */
	public void setType(String type);

	@Override
	public CommerceOrderAttachment cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}
// LIFERAY-SERVICE-BUILDER-HASH:-2108608691