export enum MetricName {
	Abandonments = 'abandonmentsMetric',
	AnonymousVisitors = 'anonymousVisitorsMetric',
	AvgTimeOnPage = 'avgTimeOnPageMetric',
	BounceRate = 'bounceRateMetric',
	Comments = 'commentsMetric',
	CompletionTime = 'completionTimeMetric',
	Downloads = 'downloadsMetric',
	Entrances = 'entrancesMetric',
	ExitRate = 'exitRateMetric',
	Impressions = 'impressionMadeMetric',
	KnownVisitors = 'knownVisitorsMetric',
	Ratings = 'ratingsMetric',
	ReadingTime = 'readingTimeMetric',
	SessionsDuration = 'sessionDurationMetric',
	SessionsPerVisitor = 'sessionsPerVisitorMetric',
	Submissions = 'submissionsMetric',
	Views = 'viewsMetric',
	Visitors = 'visitorsMetric',
}
