/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.layout.page.template.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ExternalReferenceCodeModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.model.change.tracking.CTModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the LayoutPageTemplateStructureRelElementVariationAudienceEntryRel service. Represents a row in the &quot;LPTSREVAudienceEntryRel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.layout.page.template.model.impl.LayoutPageTemplateStructureRelElementVariationAudienceEntryRelModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.layout.page.template.model.impl.LayoutPageTemplateStructureRelElementVariationAudienceEntryRelImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LayoutPageTemplateStructureRelElementVariationAudienceEntryRel
 * @generated
 */
@ProviderType
public interface
	LayoutPageTemplateStructureRelElementVariationAudienceEntryRelModel
		extends BaseModel
			<LayoutPageTemplateStructureRelElementVariationAudienceEntryRel>,
				CTModel
					<LayoutPageTemplateStructureRelElementVariationAudienceEntryRel>,
				ExternalReferenceCodeModel, GroupedModel, MVCCModel,
				ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a layout page template structure rel element variation audience entry rel model instance should use the {@link LayoutPageTemplateStructureRelElementVariationAudienceEntryRel} interface instead.
	 */

	/**
	 * Returns the primary key of this layout page template structure rel element variation audience entry rel.
	 *
	 * @return the primary key of this layout page template structure rel element variation audience entry rel
	 */
	@Override
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this layout page template structure rel element variation audience entry rel.
	 *
	 * @param primaryKey the primary key of this layout page template structure rel element variation audience entry rel
	 */
	@Override
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this layout page template structure rel element variation audience entry rel.
	 *
	 * @return the mvcc version of this layout page template structure rel element variation audience entry rel
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this layout page template structure rel element variation audience entry rel.
	 *
	 * @param mvccVersion the mvcc version of this layout page template structure rel element variation audience entry rel
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the ct collection ID of this layout page template structure rel element variation audience entry rel.
	 *
	 * @return the ct collection ID of this layout page template structure rel element variation audience entry rel
	 */
	@Override
	public long getCtCollectionId();

	/**
	 * Sets the ct collection ID of this layout page template structure rel element variation audience entry rel.
	 *
	 * @param ctCollectionId the ct collection ID of this layout page template structure rel element variation audience entry rel
	 */
	@Override
	public void setCtCollectionId(long ctCollectionId);

	/**
	 * Returns the uuid of this layout page template structure rel element variation audience entry rel.
	 *
	 * @return the uuid of this layout page template structure rel element variation audience entry rel
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this layout page template structure rel element variation audience entry rel.
	 *
	 * @param uuid the uuid of this layout page template structure rel element variation audience entry rel
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the external reference code of this layout page template structure rel element variation audience entry rel.
	 *
	 * @return the external reference code of this layout page template structure rel element variation audience entry rel
	 */
	@AutoEscape
	@Override
	public String getExternalReferenceCode();

	/**
	 * Sets the external reference code of this layout page template structure rel element variation audience entry rel.
	 *
	 * @param externalReferenceCode the external reference code of this layout page template structure rel element variation audience entry rel
	 */
	@Override
	public void setExternalReferenceCode(String externalReferenceCode);

	/**
	 * Returns the layout page template structure rel element variation audience entry rel ID of this layout page template structure rel element variation audience entry rel.
	 *
	 * @return the layout page template structure rel element variation audience entry rel ID of this layout page template structure rel element variation audience entry rel
	 */
	public long
		getLayoutPageTemplateStructureRelElementVariationAudienceEntryRelId();

	/**
	 * Sets the layout page template structure rel element variation audience entry rel ID of this layout page template structure rel element variation audience entry rel.
	 *
	 * @param layoutPageTemplateStructureRelElementVariationAudienceEntryRelId the layout page template structure rel element variation audience entry rel ID of this layout page template structure rel element variation audience entry rel
	 */
	public void
		setLayoutPageTemplateStructureRelElementVariationAudienceEntryRelId(
			long
				layoutPageTemplateStructureRelElementVariationAudienceEntryRelId);

	/**
	 * Returns the group ID of this layout page template structure rel element variation audience entry rel.
	 *
	 * @return the group ID of this layout page template structure rel element variation audience entry rel
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this layout page template structure rel element variation audience entry rel.
	 *
	 * @param groupId the group ID of this layout page template structure rel element variation audience entry rel
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this layout page template structure rel element variation audience entry rel.
	 *
	 * @return the company ID of this layout page template structure rel element variation audience entry rel
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this layout page template structure rel element variation audience entry rel.
	 *
	 * @param companyId the company ID of this layout page template structure rel element variation audience entry rel
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this layout page template structure rel element variation audience entry rel.
	 *
	 * @return the user ID of this layout page template structure rel element variation audience entry rel
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this layout page template structure rel element variation audience entry rel.
	 *
	 * @param userId the user ID of this layout page template structure rel element variation audience entry rel
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this layout page template structure rel element variation audience entry rel.
	 *
	 * @return the user uuid of this layout page template structure rel element variation audience entry rel
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this layout page template structure rel element variation audience entry rel.
	 *
	 * @param userUuid the user uuid of this layout page template structure rel element variation audience entry rel
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this layout page template structure rel element variation audience entry rel.
	 *
	 * @return the user name of this layout page template structure rel element variation audience entry rel
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this layout page template structure rel element variation audience entry rel.
	 *
	 * @param userName the user name of this layout page template structure rel element variation audience entry rel
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this layout page template structure rel element variation audience entry rel.
	 *
	 * @return the create date of this layout page template structure rel element variation audience entry rel
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this layout page template structure rel element variation audience entry rel.
	 *
	 * @param createDate the create date of this layout page template structure rel element variation audience entry rel
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this layout page template structure rel element variation audience entry rel.
	 *
	 * @return the modified date of this layout page template structure rel element variation audience entry rel
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this layout page template structure rel element variation audience entry rel.
	 *
	 * @param modifiedDate the modified date of this layout page template structure rel element variation audience entry rel
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the audience entry erc of this layout page template structure rel element variation audience entry rel.
	 *
	 * @return the audience entry erc of this layout page template structure rel element variation audience entry rel
	 */
	@AutoEscape
	public String getAudienceEntryERC();

	/**
	 * Sets the audience entry erc of this layout page template structure rel element variation audience entry rel.
	 *
	 * @param audienceEntryERC the audience entry erc of this layout page template structure rel element variation audience entry rel
	 */
	public void setAudienceEntryERC(String audienceEntryERC);

	/**
	 * Returns the layout page template structure rel element variation erc of this layout page template structure rel element variation audience entry rel.
	 *
	 * @return the layout page template structure rel element variation erc of this layout page template structure rel element variation audience entry rel
	 */
	@AutoEscape
	public String getLayoutPageTemplateStructureRelElementVariationERC();

	/**
	 * Sets the layout page template structure rel element variation erc of this layout page template structure rel element variation audience entry rel.
	 *
	 * @param layoutPageTemplateStructureRelElementVariationERC the layout page template structure rel element variation erc of this layout page template structure rel element variation audience entry rel
	 */
	public void setLayoutPageTemplateStructureRelElementVariationERC(
		String layoutPageTemplateStructureRelElementVariationERC);

	@Override
	public LayoutPageTemplateStructureRelElementVariationAudienceEntryRel
		cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}
// LIFERAY-SERVICE-BUILDER-HASH:741881618