/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.tools.service.builder.test.service.base;

import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.CurrentConnectionUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.spring.extender.service.ServiceReference;
import com.liferay.portal.tools.service.builder.test.model.CacheReplicatorEntry;
import com.liferay.portal.tools.service.builder.test.service.CacheReplicatorEntryLocalService;
import com.liferay.portal.tools.service.builder.test.service.CacheReplicatorEntryLocalServiceUtil;
import com.liferay.portal.tools.service.builder.test.service.persistence.CacheReplicatorEntryPersistence;

import java.io.Serializable;

import java.sql.Connection;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the cache replicator entry local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.portal.tools.service.builder.test.service.impl.CacheReplicatorEntryLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.portal.tools.service.builder.test.service.impl.CacheReplicatorEntryLocalServiceImpl
 * @generated
 */
public abstract class CacheReplicatorEntryLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements CacheReplicatorEntryLocalService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>CacheReplicatorEntryLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>CacheReplicatorEntryLocalServiceUtil</code>.
	 */

	/**
	 * Adds the cache replicator entry to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect CacheReplicatorEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param cacheReplicatorEntry the cache replicator entry
	 * @return the cache replicator entry that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public CacheReplicatorEntry addCacheReplicatorEntry(
		CacheReplicatorEntry cacheReplicatorEntry) {

		cacheReplicatorEntry.setNew(true);

		return cacheReplicatorEntryPersistence.update(cacheReplicatorEntry);
	}

	/**
	 * Creates a new cache replicator entry with the primary key. Does not add the cache replicator entry to the database.
	 *
	 * @param cacheReplicatorEntryId the primary key for the new cache replicator entry
	 * @return the new cache replicator entry
	 */
	@Override
	@Transactional(enabled = false)
	public CacheReplicatorEntry createCacheReplicatorEntry(
		long cacheReplicatorEntryId) {

		return cacheReplicatorEntryPersistence.create(cacheReplicatorEntryId);
	}

	/**
	 * Deletes the cache replicator entry with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect CacheReplicatorEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param cacheReplicatorEntryId the primary key of the cache replicator entry
	 * @return the cache replicator entry that was removed
	 * @throws PortalException if a cache replicator entry with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public CacheReplicatorEntry deleteCacheReplicatorEntry(
			long cacheReplicatorEntryId)
		throws PortalException {

		return cacheReplicatorEntryPersistence.remove(cacheReplicatorEntryId);
	}

	/**
	 * Deletes the cache replicator entry from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect CacheReplicatorEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param cacheReplicatorEntry the cache replicator entry
	 * @return the cache replicator entry that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public CacheReplicatorEntry deleteCacheReplicatorEntry(
		CacheReplicatorEntry cacheReplicatorEntry) {

		return cacheReplicatorEntryPersistence.remove(cacheReplicatorEntry);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return cacheReplicatorEntryPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			CacheReplicatorEntry.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return cacheReplicatorEntryPersistence.findWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.portal.tools.service.builder.test.model.impl.CacheReplicatorEntryModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return cacheReplicatorEntryPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.portal.tools.service.builder.test.model.impl.CacheReplicatorEntryModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return cacheReplicatorEntryPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return cacheReplicatorEntryPersistence.countWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return cacheReplicatorEntryPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public CacheReplicatorEntry fetchCacheReplicatorEntry(
		long cacheReplicatorEntryId) {

		return cacheReplicatorEntryPersistence.fetchByPrimaryKey(
			cacheReplicatorEntryId);
	}

	/**
	 * Returns the cache replicator entry with the primary key.
	 *
	 * @param cacheReplicatorEntryId the primary key of the cache replicator entry
	 * @return the cache replicator entry
	 * @throws PortalException if a cache replicator entry with the primary key could not be found
	 */
	@Override
	public CacheReplicatorEntry getCacheReplicatorEntry(
			long cacheReplicatorEntryId)
		throws PortalException {

		return cacheReplicatorEntryPersistence.findByPrimaryKey(
			cacheReplicatorEntryId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			cacheReplicatorEntryLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(CacheReplicatorEntry.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"cacheReplicatorEntryId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			cacheReplicatorEntryLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(
			CacheReplicatorEntry.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"cacheReplicatorEntryId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			cacheReplicatorEntryLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(CacheReplicatorEntry.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"cacheReplicatorEntryId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return cacheReplicatorEntryPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		if (_log.isWarnEnabled()) {
			_log.warn(
				"Implement CacheReplicatorEntryLocalServiceImpl#deleteCacheReplicatorEntry(CacheReplicatorEntry) to avoid orphaned data");
		}

		return cacheReplicatorEntryLocalService.deleteCacheReplicatorEntry(
			(CacheReplicatorEntry)persistedModel);
	}

	@Override
	public BasePersistence<CacheReplicatorEntry> getBasePersistence() {
		return cacheReplicatorEntryPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return cacheReplicatorEntryPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the cache replicator entries.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.portal.tools.service.builder.test.model.impl.CacheReplicatorEntryModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of cache replicator entries
	 * @param end the upper bound of the range of cache replicator entries (not inclusive)
	 * @return the range of cache replicator entries
	 */
	@Override
	public List<CacheReplicatorEntry> getCacheReplicatorEntries(
		int start, int end) {

		return cacheReplicatorEntryPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of cache replicator entries.
	 *
	 * @return the number of cache replicator entries
	 */
	@Override
	public int getCacheReplicatorEntriesCount() {
		return cacheReplicatorEntryPersistence.countAll();
	}

	/**
	 * Updates the cache replicator entry in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect CacheReplicatorEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param cacheReplicatorEntry the cache replicator entry
	 * @return the cache replicator entry that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public CacheReplicatorEntry updateCacheReplicatorEntry(
		CacheReplicatorEntry cacheReplicatorEntry) {

		return cacheReplicatorEntryPersistence.update(cacheReplicatorEntry);
	}

	/**
	 * Returns the cache replicator entry local service.
	 *
	 * @return the cache replicator entry local service
	 */
	public CacheReplicatorEntryLocalService
		getCacheReplicatorEntryLocalService() {

		return cacheReplicatorEntryLocalService;
	}

	/**
	 * Sets the cache replicator entry local service.
	 *
	 * @param cacheReplicatorEntryLocalService the cache replicator entry local service
	 */
	public void setCacheReplicatorEntryLocalService(
		CacheReplicatorEntryLocalService cacheReplicatorEntryLocalService) {

		this.cacheReplicatorEntryLocalService =
			cacheReplicatorEntryLocalService;
	}

	/**
	 * Returns the cache replicator entry persistence.
	 *
	 * @return the cache replicator entry persistence
	 */
	public CacheReplicatorEntryPersistence
		getCacheReplicatorEntryPersistence() {

		return cacheReplicatorEntryPersistence;
	}

	/**
	 * Sets the cache replicator entry persistence.
	 *
	 * @param cacheReplicatorEntryPersistence the cache replicator entry persistence
	 */
	public void setCacheReplicatorEntryPersistence(
		CacheReplicatorEntryPersistence cacheReplicatorEntryPersistence) {

		this.cacheReplicatorEntryPersistence = cacheReplicatorEntryPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService
		getCounterLocalService() {

		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService
			counterLocalService) {

		this.counterLocalService = counterLocalService;
	}

	public void afterPropertiesSet() {
		CacheReplicatorEntryLocalServiceUtil.setService(
			cacheReplicatorEntryLocalService);
	}

	public void destroy() {
		CacheReplicatorEntryLocalServiceUtil.setService(null);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return CacheReplicatorEntryLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return CacheReplicatorEntry.class;
	}

	protected String getModelClassName() {
		return CacheReplicatorEntry.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		DataSource dataSource = cacheReplicatorEntryPersistence.getDataSource();

		DB db = DBManagerUtil.getDB();

		Connection currentConnection = CurrentConnectionUtil.getConnection(
			dataSource);

		try {
			if (currentConnection != null) {
				db.runSQL(currentConnection, new String[] {sql});

				return;
			}

			try (Connection connection = dataSource.getConnection()) {
				db.runSQL(connection, new String[] {sql});
			}
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@BeanReference(type = CacheReplicatorEntryLocalService.class)
	protected CacheReplicatorEntryLocalService cacheReplicatorEntryLocalService;

	@BeanReference(type = CacheReplicatorEntryPersistence.class)
	protected CacheReplicatorEntryPersistence cacheReplicatorEntryPersistence;

	@ServiceReference(
		type = com.liferay.counter.kernel.service.CounterLocalService.class
	)
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		CacheReplicatorEntryLocalServiceBaseImpl.class);

}
// LIFERAY-SERVICE-BUILDER-HASH:2109129897