#
# Application
#

liferay.seo.studio.crawler.elasticsearch.host=${LIFERAY_SEO_STUDIO_CRAWLER_ELASTICSEARCH_HOST}
liferay.seo.studio.crawler.elasticsearch.port=${LIFERAY_SEO_STUDIO_CRAWLER_ELASTICSEARCH_PORT}
liferay.seo.studio.crawler.k8s.image.name=${LIFERAY_SEO_STUDIO_CRAWLER_K8S_IMAGE_NAME}
liferay.seo.studio.crawler.k8s.namespace=${LIFERAY_SEO_STUDIO_CRAWLER_K8S_NAMESPACE}
liferay.seo.studio.crawler.local.network.allowed=false

#
# LXC
#

com.liferay.lxc.dxp.domains=localhost:8080
com.liferay.lxc.dxp.mainDomain=localhost:8080
com.liferay.lxc.dxp.server.protocol=http

#
# OAuth
#

liferay-seostudio-etc-crawler-oahs.oauth2.headless.server.client.secret=${LIFERAY_SEOSTUDIO_ETC_CRAWLER_OAHS_CLIENT_SECRET:myfancypassword}

liferay.oauth.application.external.reference.codes=\
    liferay-seostudio-etc-crawler-oahs,\
    liferay-seostudio-etc-crawler-oaua

liferay.oauth.urls.excludes=/crawler,/ready

#
# Spring Boot
#

server.port=58081