export default () => ({
	__typename: 'DocumentMetric',
	assetId: '25842477',
	assetTitle: 'Deploying Liferay DXP in Amazon Web Services',
	commentsMetric: {
		__typename: 'Metric',
		histogram: {
			__typename: 'HistogramMetricBag',
			asymmetricComparison: false,
			metrics: [
				{
					__typename: 'HistogramMetric',
					key: '2025-02-17T00:00',
					previousValue: 0.0,
					previousValueKey: '2025-01-18T00:00',
					trend: {
						__typename: 'Trend',
						percentage: null,
						trendClassification: 'NEUTRAL',
					},
					value: 1.0,
					valueKey: '2025-02-17T00:00',
				},
				{
					__typename: 'HistogramMetric',
					key: '2025-02-18T00:00',
					previousValue: 0.0,
					previousValueKey: '2025-01-19T00:00',
					trend: {
						__typename: 'Trend',
						percentage: null,
						trendClassification: 'NEUTRAL',
					},
					value: 1.0,
					valueKey: '2025-02-18T00:00',
				},
			],
			total: 2,
		},
		previousValue: null,
		trend: {
			__typename: 'Trend',
			percentage: null,
			trendClassification: 'NEUTRAL',
		},
		value: 1,
	},
	downloadsMetric: {
		__typename: 'Metric',
		geolocation: [
			{
				__typename: 'Metric',
				metrics: null,
				value: 50,
				valueKey: 'United States',
			},
			{
				__typename: 'Metric',
				metrics: null,
				value: 20,
				valueKey: 'United Kingdom',
			},
			{
				__typename: 'Metric',
				metrics: null,
				value: 15,
				valueKey: 'Colombia',
			},
			{
				__typename: 'Metric',
				metrics: null,
				value: 10,
				valueKey: 'Vietnam',
			},
			{
				__typename: 'Metric',
				metrics: null,
				value: 8,
				valueKey: 'Germany',
			},
			{
				__typename: 'Metric',
				metrics: null,
				value: 7,
				valueKey: 'India',
			},
			{
				__typename: 'Metric',
				metrics: null,
				value: 5,
				valueKey: 'Mexico',
			},
			{
				__typename: 'Metric',
				metrics: null,
				value: 3,
				valueKey: 'Peru',
			},
			{
				__typename: 'Metric',
				metrics: null,
				value: 2,
				valueKey: 'Portugal',
			},
			{
				__typename: 'Metric',
				metrics: null,
				value: 2,
				valueKey: 'Spain',
			},
		],
		histogram: {
			__typename: 'HistogramMetricBag',
			asymmetricComparison: false,
			metrics: [
				{
					__typename: 'HistogramMetric',
					key: '2025-02-16T00:00',
					previousValue: 0.0,
					previousValueKey: '2025-01-17T00:00',
					trend: {
						__typename: 'Trend',
						percentage: null,
						trendClassification: 'NEUTRAL',
					},
					value: 1.0,
					valueKey: '2025-02-16T00:00',
				},
				{
					__typename: 'HistogramMetric',
					key: '2025-02-17T00:00',
					previousValue: 0.0,
					previousValueKey: '2025-01-18T00:00',
					trend: {
						__typename: 'Trend',
						percentage: null,
						trendClassification: 'NEUTRAL',
					},
					value: 2.0,
					valueKey: '2025-02-17T00:00',
				},
				{
					__typename: 'HistogramMetric',
					key: '2025-02-18T00:00',
					previousValue: 0.0,
					previousValueKey: '2025-01-19T00:00',
					trend: {
						__typename: 'Trend',
						percentage: null,
						trendClassification: 'NEUTRAL',
					},
					value: 5.0,
					valueKey: '2025-02-18T00:00',
				},
				{
					__typename: 'HistogramMetric',
					key: '2025-02-19T00:00',
					previousValue: 0.0,
					previousValueKey: '2025-01-20T00:00',
					trend: {
						__typename: 'Trend',
						percentage: null,
						trendClassification: 'NEUTRAL',
					},
					value: 0.0,
					valueKey: '2025-02-19T00:00',
				},
				{
					__typename: 'HistogramMetric',
					key: '2025-02-20T00:00',
					previousValue: 0.0,
					previousValueKey: '2025-01-21T00:00',
					trend: {
						__typename: 'Trend',
						percentage: null,
						trendClassification: 'NEUTRAL',
					},
					value: 3.0,
					valueKey: '2025-02-20T00:00',
				},
				{
					__typename: 'HistogramMetric',
					key: '2025-02-21T00:00',
					previousValue: 0.0,
					previousValueKey: '2025-01-22T00:00',
					trend: {
						__typename: 'Trend',
						percentage: null,
						trendClassification: 'NEUTRAL',
					},
					value: 0.0,
					valueKey: '2025-02-21T00:00',
				},
				{
					__typename: 'HistogramMetric',
					key: '2025-03-02T00:00',
					previousValue: 0.0,
					previousValueKey: '2025-03-01T00:00',
					trend: {
						__typename: 'Trend',
						percentage: null,
						trendClassification: 'NEUTRAL',
					},
					value: 1.0,
					valueKey: '2025-03-02T00:00',
				},
			],
			total: 7,
		},
		previousValue: 1,
		trend: {
			__typename: 'Trend',
			percentage: 0,
			trendClassification: 'UPWARD',
		},
		value: 12,
	},
	impressionMadeMetric: {
		__typename: 'Metric',
		histogram: {
			__typename: 'HistogramMetricBag',
			asymmetricComparison: false,
			metrics: [
				{
					__typename: 'HistogramMetric',
					key: '2025-02-17T00:00',
					previousValue: 0.0,
					previousValueKey: '2025-01-18T00:00',
					trend: {
						__typename: 'Trend',
						percentage: null,
						trendClassification: 'NEUTRAL',
					},
					value: 1.0,
					valueKey: '2025-02-17T00:00',
				},
				{
					__typename: 'HistogramMetric',
					key: '2025-02-18T00:00',
					previousValue: 0.0,
					previousValueKey: '2025-01-19T00:00',
					trend: {
						__typename: 'Trend',
						percentage: null,
						trendClassification: 'NEUTRAL',
					},
					value: 2.0,
					valueKey: '2025-02-18T00:00',
				},
				{
					__typename: 'HistogramMetric',
					key: '2025-02-19T00:00',
					previousValue: 0.0,
					previousValueKey: '2025-01-20T00:00',
					trend: {
						__typename: 'Trend',
						percentage: null,
						trendClassification: 'NEUTRAL',
					},
					value: 3.0,
					valueKey: '2025-02-19T00:00',
				},
			],
			total: 3,
		},
		previousValue: null,
		trend: {
			__typename: 'Trend',
			percentage: null,
			trendClassification: 'NEUTRAL',
		},
		value: 3.0,
	},
	ratingsMetric: {
		__typename: 'Metric',
		histogram: {
			__typename: 'HistogramMetricBag',
			asymmetricComparison: false,
			metrics: [
				{
					__typename: 'HistogramMetric',
					key: '2025-02-17T00:00',
					previousValue: 0.0,
					previousValueKey: '2025-01-18T00:00',
					trend: {
						__typename: 'Trend',
						percentage: null,
						trendClassification: 'NEUTRAL',
					},
					value: 0.0,
					valueKey: '2025-02-17T00:00',
				},
				{
					__typename: 'HistogramMetric',
					key: '2025-02-18T00:00',
					previousValue: 0.0,
					previousValueKey: '2025-01-19T00:00',
					trend: {
						__typename: 'Trend',
						percentage: null,
						trendClassification: 'NEUTRAL',
					},
					value: 0.0,
					valueKey: '2025-02-18T00:00',
				},
				{
					__typename: 'HistogramMetric',
					key: '2025-02-19T00:00',
					previousValue: 0.0,
					previousValueKey: '2025-01-20T00:00',
					trend: {
						__typename: 'Trend',
						percentage: null,
						trendClassification: 'NEUTRAL',
					},
					value: 0.0,
					valueKey: '2025-02-19T00:00',
				},
			],
			total: 3,
		},
		previousValue: null,
		trend: {
			__typename: 'Trend',
			percentage: null,
			trendClassification: 'NEUTRAL',
		},
		value: 0.0,
	},
});
