liferay-aws-backup-restore:
    enabled: false
liferay-default:
    configmap:
        data:
            com.liferay.portal.search.opensearch2.configuration.OpenSearchConfiguration.config: |
                remoteClusterConnectionId="REMOTE"
            com.liferay.portal.search.opensearch2.configuration.OpenSearchConnectionConfiguration-REMOTE.config: |
                active=B"true"
                authenticationEnabled=B"true"
                connectionId="REMOTE"
                httpSSLEnabled=B"false"
                networkHostAddresses=["https://$[env:OPENSEARCH_ENDPOINT]"]
                password="$[env:OPENSEARCH_PASSWORD]"
                username="$[env:OPENSEARCH_USERNAME]"
            com.liferay.portal.store.s3.configuration.S3StoreConfiguration.config: |
                accessKey=""
                bucketName="$[env:S3_BUCKET_ID]"
                s3Endpoint=""
                s3PathStyle=B"false"
                s3Region="$[env:S3_BUCKET_REGION]"
                secretKey=""
    customEnv:
        x-liferay-aws:
            -   name: LIFERAY_NETWORK_HOST_ADDRESSES
                value: https://$(OPENSEARCH_ENDPOINT):443
            -   name: LIFERAY_OPENSEARCH_ENABLED
                value: "true"
            -   name: LIFERAY_OPENSEARCH_PASSWORD
                value: $(OPENSEARCH_PASSWORD)
    customEnvFrom:
        x-liferay-aws:
            -   secretRef:
                    name: managed-service-details
    customInitContainers:
        x-liferay-install-opensearch-modules:
            -   containerTemplate: |
                    -   command:
                        -   bash
                        -   -c
                        -   |
                            function download_module {
                                {{- if eq .image.tag "latest" }}
                                local product_version="nightly"

                                local url="https://releases.liferay.com/opensearch2/${product_version}/com.liferay.portal.search.opensearch2.${1}.jar"
                                {{- else }}
                                local product_version="{{ .image.tag }}"

                                local url="https://releases.liferay.com/opensearch2/dxp/${product_version}/com.liferay.portal.search.opensearch2.${1}.jar"
                                {{- end }}

                                local http_code=$( \
                                    curl \
                                        --location \
                                        --output-dir /temp/liferay/deploy \
                                        --remote-name \
                                        --retry 5 \
                                        --retry-all-errors \
                                        --retry-delay 2 \
                                        --write-out "%{http_code}" \
                                        "${url}")

                                if [ "${http_code}" != "200" ]
                                then
                                    echo "Unable to download OpenSearch modules for product version ${product_version}." >&2

                                    exit 1
                                fi
                            }

                            function main {
                                mkdir --parents /temp/liferay/deploy

                                rm --force --verbose "/temp/osgi/modules/com.liferay.portal.search.opensearch2"*

                                download_module "api"
                                download_module "impl"
                            }

                            main
                        image: {{ printf "%s:%s" .image.repository (.image.tag | toString) }}
                        imagePullPolicy: {{ .image.pullPolicy }}
                        name: liferay-install-opensearch-modules
                        volumeMounts:
                            -   mountPath: /temp
                                name: liferay-persistent-volume
    customLabels:
        origin: liferay-aws
    customVolumeMounts:
        x-liferay-aws:
            -   mountPath: /opt/liferay/osgi/configs/com.liferay.portal.search.opensearch2.configuration.OpenSearchConfiguration.config
                name: liferay-configmap
                subPath: com.liferay.portal.search.opensearch2.configuration.OpenSearchConfiguration.config
            -   mountPath: /opt/liferay/osgi/configs/com.liferay.portal.search.opensearch2.configuration.OpenSearchConnectionConfiguration-REMOTE.config
                name: liferay-configmap
                subPath: com.liferay.portal.search.opensearch2.configuration.OpenSearchConnectionConfiguration-REMOTE.config
            -   mountPath: /opt/liferay/osgi/configs/com.liferay.portal.store.s3.configuration.S3StoreConfiguration.config
                name: liferay-configmap
                subPath: com.liferay.portal.store.s3.configuration.S3StoreConfiguration.config
    network:
        enabled: true
        timeouts:
            backendRequest: 300s
            request: 300s
    portalBundleDenyList:
        -   com.liferay.portal.search.elasticsearch.cross.cluster.replication.impl
        -   com.liferay.portal.search.elasticsearch.monitoring.web
        -   com.liferay.portal.search.elasticsearch8.api
        -   com.liferay.portal.search.elasticsearch8.impl
        -   com.liferay.portal.search.learning.to.rank.api
        -   com.liferay.portal.search.learning.to.rank.impl
    portalProperties: |
        dl.store.impl=com.liferay.portal.store.s3.S3Store
        jdbc.default.driverClassName=org.postgresql.Driver
        jdbc.default.password=${env.DATABASE_PASSWORD}
        jdbc.default.url=jdbc:postgresql://${env.DATABASE_ENDPOINT}:${env.DATABASE_PORT}/lportal?useUnicode=true&characterEncoding=UTF-8&useFastDateParsing=false
        jdbc.default.username=${env.DATABASE_USERNAME}
    resources:
        limits:
            cpu: 4000m
            memory: 12Gi
        requests:
            cpu: 2000m
            memory: 4Gi
    volumeClaimTemplates:
        -   metadata:
                name: liferay-persistent-volume
            spec:
                accessModes:
                    -   ReadWriteOnce
                resources:
                    requests:
                        storage: 10Gi
                storageClassName: gp3