/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.tools.service.builder.test.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the CacheReplicatorEntry service. Represents a row in the &quot;CacheReplicatorEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.portal.tools.service.builder.test.model.impl.CacheReplicatorEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.portal.tools.service.builder.test.model.impl.CacheReplicatorEntryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CacheReplicatorEntry
 * @generated
 */
@ProviderType
public interface CacheReplicatorEntryModel
	extends BaseModel<CacheReplicatorEntry>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a cache replicator entry model instance should use the {@link CacheReplicatorEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this cache replicator entry.
	 *
	 * @return the primary key of this cache replicator entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this cache replicator entry.
	 *
	 * @param primaryKey the primary key of this cache replicator entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the cache replicator entry ID of this cache replicator entry.
	 *
	 * @return the cache replicator entry ID of this cache replicator entry
	 */
	public long getCacheReplicatorEntryId();

	/**
	 * Sets the cache replicator entry ID of this cache replicator entry.
	 *
	 * @param cacheReplicatorEntryId the cache replicator entry ID of this cache replicator entry
	 */
	public void setCacheReplicatorEntryId(long cacheReplicatorEntryId);

	/**
	 * Returns the company ID of this cache replicator entry.
	 *
	 * @return the company ID of this cache replicator entry
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this cache replicator entry.
	 *
	 * @param companyId the company ID of this cache replicator entry
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the name of this cache replicator entry.
	 *
	 * @return the name of this cache replicator entry
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this cache replicator entry.
	 *
	 * @param name the name of this cache replicator entry
	 */
	public void setName(String name);

	@Override
	public CacheReplicatorEntry cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}
// LIFERAY-SERVICE-BUILDER-HASH:-1950042594