/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.tools.service.builder.test.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ReassociateEntry service. Represents a row in the &quot;ReassociateEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.portal.tools.service.builder.test.model.impl.ReassociateEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.portal.tools.service.builder.test.model.impl.ReassociateEntryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ReassociateEntry
 * @generated
 */
@ProviderType
public interface ReassociateEntryModel extends BaseModel<ReassociateEntry> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a reassociate entry model instance should use the {@link ReassociateEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this reassociate entry.
	 *
	 * @return the primary key of this reassociate entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this reassociate entry.
	 *
	 * @param primaryKey the primary key of this reassociate entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the reassociate entry ID of this reassociate entry.
	 *
	 * @return the reassociate entry ID of this reassociate entry
	 */
	public long getReassociateEntryId();

	/**
	 * Sets the reassociate entry ID of this reassociate entry.
	 *
	 * @param reassociateEntryId the reassociate entry ID of this reassociate entry
	 */
	public void setReassociateEntryId(long reassociateEntryId);

	/**
	 * Returns the name of this reassociate entry.
	 *
	 * @return the name of this reassociate entry
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this reassociate entry.
	 *
	 * @param name the name of this reassociate entry
	 */
	public void setName(String name);

	@Override
	public ReassociateEntry cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}
// LIFERAY-SERVICE-BUILDER-HASH:-233335631