/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.commerce.model.impl;

import com.liferay.commerce.model.CommerceOrderAttachment;
import com.liferay.commerce.service.CommerceOrderAttachmentLocalServiceUtil;

/**
 * The extended model base implementation for the CommerceOrderAttachment service. Represents a row in the &quot;CommerceOrderAttachment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CommerceOrderAttachmentImpl}.
 * </p>
 *
 * @author Alessio Antonio Rendina
 * @see CommerceOrderAttachmentImpl
 * @see CommerceOrderAttachment
 * @generated
 */
public abstract class CommerceOrderAttachmentBaseImpl
	extends CommerceOrderAttachmentModelImpl
	implements CommerceOrderAttachment {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a commerce order attachment model instance should use the <code>CommerceOrderAttachment</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			CommerceOrderAttachmentLocalServiceUtil.addCommerceOrderAttachment(
				this);
		}
		else {
			CommerceOrderAttachmentLocalServiceUtil.
				updateCommerceOrderAttachment(this);
		}
	}

}
// LIFERAY-SERVICE-BUILDER-HASH:439866670