{{- if and .Values.autoscaling.enabled (eq .Values.autoscaling.type "keda") .Values.autoscaling.keda.triggerAuthentication.spec }}
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
    {{- with .Values.autoscaling.keda.triggerAuthentication.annotations }}
    annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    labels:
        {{- include "liferay.labels" . | nindent 8 }}
    name: {{ include "liferay.name" . }}
    namespace: {{ include "liferay.namespace" . }}
spec:
    {{- toYaml .Values.autoscaling.keda.triggerAuthentication.spec | nindent 4 }}
{{- end }}