{{- if and .Values.gateway.className .Values.gateway.envoyProxyRoleArn .Values.gateway.namespace }}
{{- $gatewayProxyConfigName := "liferay-proxy-config" }}
{{- $loadBalancerScheme := "internal" }}
{{- if .Values.gateway.internetFacing }}
{{- $loadBalancerScheme = "internet-facing" }}
{{- end }}
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: "-110"
    labels:
        app: liferay
        component: gateway
    name: {{ $gatewayProxyConfigName }}
    namespace: {{ .Values.gateway.namespace }}
spec:
    provider:
        kubernetes:
            envoyDeployment:
                pod:
                    annotations:
                        "eks.amazonaws.com/role-arn": {{ .Values.gateway.envoyProxyRoleArn | quote }}
                    topologySpreadConstraints:
                        -   labelSelector:
                                matchLabels:
                                    app.kubernetes.io/name: envoy
                            maxSkew: 1
                            topologyKey: kubernetes.io/hostname
                            whenUnsatisfiable: ScheduleAnyway
                replicas: 3
            envoyHpa:
                maxReplicas: 10
                metrics:
                    -   resource:
                            name: cpu
                            target:
                                averageUtilization: 75
                                type: Utilization
                        type: Resource
                minReplicas: 3
            envoyService:
                annotations:
                    "service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags": "DeploymentName={{ .Values.deploymentName }}"
                    "service.beta.kubernetes.io/aws-load-balancer-attributes": "load_balancing.cross_zone.enabled=true"
                    "service.beta.kubernetes.io/aws-load-balancer-healthcheck-path": /ready
                    "service.beta.kubernetes.io/aws-load-balancer-healthcheck-port": "19003"
                    "service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol": HTTP
                    "service.beta.kubernetes.io/aws-load-balancer-nlb-target-type": ip
                    "service.beta.kubernetes.io/aws-load-balancer-proxy-protocol": "*"
                    "service.beta.kubernetes.io/aws-load-balancer-scheme": {{ $loadBalancerScheme }}
                    "service.beta.kubernetes.io/aws-load-balancer-target-group-attributes": "proxy_protocol_v2.enabled=true"
                    "service.beta.kubernetes.io/aws-load-balancer-type": external
                externalTrafficPolicy: Local
                type: LoadBalancer
        type: Kubernetes
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: "-110"
    labels:
        app: liferay
        component: gateway
    name: {{ .Values.gateway.className }}
spec:
    controllerName: gateway.envoyproxy.io/gatewayclass-controller
    parametersRef:
        group: gateway.envoyproxy.io
        kind: EnvoyProxy
        name: {{ $gatewayProxyConfigName }}
        namespace: {{ .Values.gateway.namespace }}
{{- end -}}