/**
 * SPDX-FileCopyrightText: (c) 2000 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

import getExportedSymbols from './getExportedSymbols.mjs';
import getURL, {URLType} from './getURL.mjs';

/**
 * Return the content of an import bridge file that can be used by esbuild as an
 * entry point.
 *
 * Import bridges are necessary since we need esbuild to import symbols using
 * standard ESM syntax and for that to happen it must be fed an ES module as
 * entry point. If fed a CommonJS one esbuild will refuse to export things as
 * ESM syntax.
 */
export default async function getImportBridgeJavaScript(
	overridenPackageSymbols,
	urlPrefix,
	webContextPath,
	moduleName
) {
	const symbols = await getExportedSymbols(
		overridenPackageSymbols,
		moduleName
	);

	delete symbols.__esModule;

	const namedExportSymbols = Object.keys(symbols)
		.filter((symbol) => symbol !== 'default')
		.join(',\n');

	//
	// If the exported object was generated by a harmony aware tool, we
	// directly export the symbols as is.
	//
	// Otherwise, we need to set default to the exported object so that
	// other modules can find it when they are interoperated by tools like
	// babel or webpack.
	//
	// Note that we need to use import from instead of require in the generated
	// source because otherwise esbuild fails to honor "browser" field of
	// package.json files.
	//

	const moduleURL = getURL(
		URLType.NPM_EXPORT,
		urlPrefix,
		webContextPath,
		moduleName
	);

	let source = `
export {${namedExportSymbols}} from '${moduleURL}';
`;

	if (symbols.default) {
		source += `import __x__ from '${moduleURL}';`;
		source += `export default __x__;`;
	}

	return source;
}
