/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.layout.page.template.service.base;

import com.liferay.layout.page.template.model.LayoutPageTemplateStructureRelElementVariationAudienceEntryRel;
import com.liferay.layout.page.template.service.LayoutPageTemplateStructureRelElementVariationAudienceEntryRelService;
import com.liferay.layout.page.template.service.persistence.LayoutPageTemplateStructureRelElementVariationAudienceEntryRelPersistence;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.CurrentConnectionUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;

import java.sql.Connection;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the layout page template structure rel element variation audience entry rel remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.layout.page.template.service.impl.LayoutPageTemplateStructureRelElementVariationAudienceEntryRelServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.layout.page.template.service.impl.LayoutPageTemplateStructureRelElementVariationAudienceEntryRelServiceImpl
 * @generated
 */
public abstract class
	LayoutPageTemplateStructureRelElementVariationAudienceEntryRelServiceBaseImpl
		extends BaseServiceImpl
		implements AopService, IdentifiableOSGiService,
				   LayoutPageTemplateStructureRelElementVariationAudienceEntryRelService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>LayoutPageTemplateStructureRelElementVariationAudienceEntryRelService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>com.liferay.layout.page.template.service.LayoutPageTemplateStructureRelElementVariationAudienceEntryRelServiceUtil</code>.
	 */
	@Deactivate
	protected void deactivate() {
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			LayoutPageTemplateStructureRelElementVariationAudienceEntryRelService.class,
			IdentifiableOSGiService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		layoutPageTemplateStructureRelElementVariationAudienceEntryRelService =
			(LayoutPageTemplateStructureRelElementVariationAudienceEntryRelService)
				aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return LayoutPageTemplateStructureRelElementVariationAudienceEntryRelService.class.
			getName();
	}

	protected Class<?> getModelClass() {
		return LayoutPageTemplateStructureRelElementVariationAudienceEntryRel.
			class;
	}

	protected String getModelClassName() {
		return LayoutPageTemplateStructureRelElementVariationAudienceEntryRel.
			class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		DataSource dataSource =
			layoutPageTemplateStructureRelElementVariationAudienceEntryRelPersistence.
				getDataSource();

		DB db = DBManagerUtil.getDB();

		Connection currentConnection = CurrentConnectionUtil.getConnection(
			dataSource);

		try {
			if (currentConnection != null) {
				db.runSQL(currentConnection, new String[] {sql});

				return;
			}

			try (Connection connection = dataSource.getConnection()) {
				db.runSQL(connection, new String[] {sql});
			}
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@Reference
	protected com.liferay.layout.page.template.service.
		LayoutPageTemplateStructureRelElementVariationAudienceEntryRelLocalService
			layoutPageTemplateStructureRelElementVariationAudienceEntryRelLocalService;

	protected
		LayoutPageTemplateStructureRelElementVariationAudienceEntryRelService
			layoutPageTemplateStructureRelElementVariationAudienceEntryRelService;

	@Reference
	protected
		LayoutPageTemplateStructureRelElementVariationAudienceEntryRelPersistence
			layoutPageTemplateStructureRelElementVariationAudienceEntryRelPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		LayoutPageTemplateStructureRelElementVariationAudienceEntryRelServiceBaseImpl.class);

}
// LIFERAY-SERVICE-BUILDER-HASH:-603331895