/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.layout.page.template.service.base;

import com.liferay.exportimport.kernel.lar.ExportImportHelperUtil;
import com.liferay.exportimport.kernel.lar.ManifestSummary;
import com.liferay.exportimport.kernel.lar.PortletDataContext;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.layout.page.template.model.LayoutPageTemplateStructureRelElementVariationAudienceEntryRel;
import com.liferay.layout.page.template.service.LayoutPageTemplateStructureRelElementVariationAudienceEntryRelLocalService;
import com.liferay.layout.page.template.service.persistence.LayoutPageTemplateStructureRelElementVariationAudienceEntryRelPersistence;
import com.liferay.petra.function.UnsafeFunction;
import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.CurrentConnectionUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ExportActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.change.tracking.CTService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.service.persistence.change.tracking.CTPersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.sql.Connection;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the layout page template structure rel element variation audience entry rel local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.layout.page.template.service.impl.LayoutPageTemplateStructureRelElementVariationAudienceEntryRelLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.layout.page.template.service.impl.LayoutPageTemplateStructureRelElementVariationAudienceEntryRelLocalServiceImpl
 * @generated
 */
public abstract class
	LayoutPageTemplateStructureRelElementVariationAudienceEntryRelLocalServiceBaseImpl
		extends BaseLocalServiceImpl
		implements AopService, IdentifiableOSGiService,
				   LayoutPageTemplateStructureRelElementVariationAudienceEntryRelLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>LayoutPageTemplateStructureRelElementVariationAudienceEntryRelLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>com.liferay.layout.page.template.service.LayoutPageTemplateStructureRelElementVariationAudienceEntryRelLocalServiceUtil</code>.
	 */

	/**
	 * Adds the layout page template structure rel element variation audience entry rel to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect LayoutPageTemplateStructureRelElementVariationAudienceEntryRelLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param layoutPageTemplateStructureRelElementVariationAudienceEntryRel the layout page template structure rel element variation audience entry rel
	 * @return the layout page template structure rel element variation audience entry rel that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public LayoutPageTemplateStructureRelElementVariationAudienceEntryRel
		addLayoutPageTemplateStructureRelElementVariationAudienceEntryRel(
			LayoutPageTemplateStructureRelElementVariationAudienceEntryRel
				layoutPageTemplateStructureRelElementVariationAudienceEntryRel) {

		layoutPageTemplateStructureRelElementVariationAudienceEntryRel.setNew(
			true);

		return layoutPageTemplateStructureRelElementVariationAudienceEntryRelPersistence.
			update(
				layoutPageTemplateStructureRelElementVariationAudienceEntryRel);
	}

	/**
	 * Creates a new layout page template structure rel element variation audience entry rel with the primary key. Does not add the layout page template structure rel element variation audience entry rel to the database.
	 *
	 * @param layoutPageTemplateStructureRelElementVariationAudienceEntryRelId the primary key for the new layout page template structure rel element variation audience entry rel
	 * @return the new layout page template structure rel element variation audience entry rel
	 */
	@Override
	@Transactional(enabled = false)
	public LayoutPageTemplateStructureRelElementVariationAudienceEntryRel
		createLayoutPageTemplateStructureRelElementVariationAudienceEntryRel(
			long
				layoutPageTemplateStructureRelElementVariationAudienceEntryRelId) {

		return layoutPageTemplateStructureRelElementVariationAudienceEntryRelPersistence.
			create(
				layoutPageTemplateStructureRelElementVariationAudienceEntryRelId);
	}

	/**
	 * Deletes the layout page template structure rel element variation audience entry rel with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect LayoutPageTemplateStructureRelElementVariationAudienceEntryRelLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param layoutPageTemplateStructureRelElementVariationAudienceEntryRelId the primary key of the layout page template structure rel element variation audience entry rel
	 * @return the layout page template structure rel element variation audience entry rel that was removed
	 * @throws PortalException if a layout page template structure rel element variation audience entry rel with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public LayoutPageTemplateStructureRelElementVariationAudienceEntryRel
			deleteLayoutPageTemplateStructureRelElementVariationAudienceEntryRel(
				long
					layoutPageTemplateStructureRelElementVariationAudienceEntryRelId)
		throws PortalException {

		return layoutPageTemplateStructureRelElementVariationAudienceEntryRelPersistence.
			remove(
				layoutPageTemplateStructureRelElementVariationAudienceEntryRelId);
	}

	/**
	 * Deletes the layout page template structure rel element variation audience entry rel from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect LayoutPageTemplateStructureRelElementVariationAudienceEntryRelLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param layoutPageTemplateStructureRelElementVariationAudienceEntryRel the layout page template structure rel element variation audience entry rel
	 * @return the layout page template structure rel element variation audience entry rel that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public LayoutPageTemplateStructureRelElementVariationAudienceEntryRel
		deleteLayoutPageTemplateStructureRelElementVariationAudienceEntryRel(
			LayoutPageTemplateStructureRelElementVariationAudienceEntryRel
				layoutPageTemplateStructureRelElementVariationAudienceEntryRel) {

		return layoutPageTemplateStructureRelElementVariationAudienceEntryRelPersistence.
			remove(
				layoutPageTemplateStructureRelElementVariationAudienceEntryRel);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return layoutPageTemplateStructureRelElementVariationAudienceEntryRelPersistence.
			dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			LayoutPageTemplateStructureRelElementVariationAudienceEntryRel.
				class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return layoutPageTemplateStructureRelElementVariationAudienceEntryRelPersistence.
			findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.layout.page.template.model.impl.LayoutPageTemplateStructureRelElementVariationAudienceEntryRelModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return layoutPageTemplateStructureRelElementVariationAudienceEntryRelPersistence.
			findWithDynamicQuery(dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.layout.page.template.model.impl.LayoutPageTemplateStructureRelElementVariationAudienceEntryRelModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return layoutPageTemplateStructureRelElementVariationAudienceEntryRelPersistence.
			findWithDynamicQuery(dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return layoutPageTemplateStructureRelElementVariationAudienceEntryRelPersistence.
			countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return layoutPageTemplateStructureRelElementVariationAudienceEntryRelPersistence.
			countWithDynamicQuery(dynamicQuery, projection);
	}

	@Override
	public LayoutPageTemplateStructureRelElementVariationAudienceEntryRel
		fetchLayoutPageTemplateStructureRelElementVariationAudienceEntryRel(
			long
				layoutPageTemplateStructureRelElementVariationAudienceEntryRelId) {

		return layoutPageTemplateStructureRelElementVariationAudienceEntryRelPersistence.
			fetchByPrimaryKey(
				layoutPageTemplateStructureRelElementVariationAudienceEntryRelId);
	}

	/**
	 * Returns the layout page template structure rel element variation audience entry rel matching the UUID and group.
	 *
	 * @param uuid the layout page template structure rel element variation audience entry rel's UUID
	 * @param groupId the primary key of the group
	 * @return the matching layout page template structure rel element variation audience entry rel, or <code>null</code> if a matching layout page template structure rel element variation audience entry rel could not be found
	 */
	@Override
	public LayoutPageTemplateStructureRelElementVariationAudienceEntryRel
		fetchLayoutPageTemplateStructureRelElementVariationAudienceEntryRelByUuidAndGroupId(
			String uuid, long groupId) {

		return layoutPageTemplateStructureRelElementVariationAudienceEntryRelPersistence.
			fetchByUUID_G(uuid, groupId);
	}

	@Override
	public LayoutPageTemplateStructureRelElementVariationAudienceEntryRel
		fetchLayoutPageTemplateStructureRelElementVariationAudienceEntryRelByExternalReferenceCode(
			String externalReferenceCode, long groupId) {

		return layoutPageTemplateStructureRelElementVariationAudienceEntryRelPersistence.
			fetchByERC_G(externalReferenceCode, groupId);
	}

	@Override
	public LayoutPageTemplateStructureRelElementVariationAudienceEntryRel
			getLayoutPageTemplateStructureRelElementVariationAudienceEntryRelByExternalReferenceCode(
				String externalReferenceCode, long groupId)
		throws PortalException {

		return layoutPageTemplateStructureRelElementVariationAudienceEntryRelPersistence.
			findByERC_G(externalReferenceCode, groupId);
	}

	/**
	 * Returns the layout page template structure rel element variation audience entry rel with the primary key.
	 *
	 * @param layoutPageTemplateStructureRelElementVariationAudienceEntryRelId the primary key of the layout page template structure rel element variation audience entry rel
	 * @return the layout page template structure rel element variation audience entry rel
	 * @throws PortalException if a layout page template structure rel element variation audience entry rel with the primary key could not be found
	 */
	@Override
	public LayoutPageTemplateStructureRelElementVariationAudienceEntryRel
			getLayoutPageTemplateStructureRelElementVariationAudienceEntryRel(
				long
					layoutPageTemplateStructureRelElementVariationAudienceEntryRelId)
		throws PortalException {

		return layoutPageTemplateStructureRelElementVariationAudienceEntryRelPersistence.
			findByPrimaryKey(
				layoutPageTemplateStructureRelElementVariationAudienceEntryRelId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			layoutPageTemplateStructureRelElementVariationAudienceEntryRelLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(
			LayoutPageTemplateStructureRelElementVariationAudienceEntryRel.
				class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"layoutPageTemplateStructureRelElementVariationAudienceEntryRelId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			layoutPageTemplateStructureRelElementVariationAudienceEntryRelLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(
			LayoutPageTemplateStructureRelElementVariationAudienceEntryRel.
				class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"layoutPageTemplateStructureRelElementVariationAudienceEntryRelId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			layoutPageTemplateStructureRelElementVariationAudienceEntryRelLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(
			LayoutPageTemplateStructureRelElementVariationAudienceEntryRel.
				class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"layoutPageTemplateStructureRelElementVariationAudienceEntryRelId");
	}

	@Override
	public ExportActionableDynamicQuery getExportActionableDynamicQuery(
		final PortletDataContext portletDataContext) {

		final ExportActionableDynamicQuery exportActionableDynamicQuery =
			new ExportActionableDynamicQuery() {

				@Override
				public long performCount() throws PortalException {
					ManifestSummary manifestSummary =
						portletDataContext.getManifestSummary();

					StagedModelType stagedModelType = getStagedModelType();

					long modelAdditionCount = super.performCount();

					manifestSummary.addModelAdditionCount(
						stagedModelType, modelAdditionCount);

					long modelDeletionCount =
						ExportImportHelperUtil.getModelDeletionCount(
							portletDataContext, stagedModelType);

					manifestSummary.addModelDeletionCount(
						stagedModelType, modelDeletionCount);

					return modelAdditionCount;
				}

			};

		initActionableDynamicQuery(exportActionableDynamicQuery);

		exportActionableDynamicQuery.setAddCriteriaMethod(
			new ActionableDynamicQuery.AddCriteriaMethod() {

				@Override
				public void addCriteria(DynamicQuery dynamicQuery) {
					portletDataContext.addDateRangeCriteria(
						dynamicQuery, "modifiedDate");
				}

			});

		exportActionableDynamicQuery.setCompanyId(
			portletDataContext.getCompanyId());

		exportActionableDynamicQuery.setPerformActionMethod(
			new ActionableDynamicQuery.PerformActionMethod
				<LayoutPageTemplateStructureRelElementVariationAudienceEntryRel>() {

				@Override
				public void performAction(
						LayoutPageTemplateStructureRelElementVariationAudienceEntryRel
							layoutPageTemplateStructureRelElementVariationAudienceEntryRel)
					throws PortalException {

					StagedModelDataHandlerUtil.exportStagedModel(
						portletDataContext,
						layoutPageTemplateStructureRelElementVariationAudienceEntryRel);
				}

			});
		exportActionableDynamicQuery.setStagedModelType(
			new StagedModelType(
				PortalUtil.getClassNameId(
					LayoutPageTemplateStructureRelElementVariationAudienceEntryRel.class.
						getName())));

		return exportActionableDynamicQuery;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return layoutPageTemplateStructureRelElementVariationAudienceEntryRelPersistence.
			create(((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		if (_log.isWarnEnabled()) {
			_log.warn(
				"Implement LayoutPageTemplateStructureRelElementVariationAudienceEntryRelLocalServiceImpl#deleteLayoutPageTemplateStructureRelElementVariationAudienceEntryRel(LayoutPageTemplateStructureRelElementVariationAudienceEntryRel) to avoid orphaned data");
		}

		return layoutPageTemplateStructureRelElementVariationAudienceEntryRelLocalService.
			deleteLayoutPageTemplateStructureRelElementVariationAudienceEntryRel(
				(LayoutPageTemplateStructureRelElementVariationAudienceEntryRel)
					persistedModel);
	}

	@Override
	public BasePersistence
		<LayoutPageTemplateStructureRelElementVariationAudienceEntryRel>
			getBasePersistence() {

		return layoutPageTemplateStructureRelElementVariationAudienceEntryRelPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return layoutPageTemplateStructureRelElementVariationAudienceEntryRelPersistence.
			findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns all the layout page template structure rel element variation audience entry rels matching the UUID and company.
	 *
	 * @param uuid the UUID of the layout page template structure rel element variation audience entry rels
	 * @param companyId the primary key of the company
	 * @return the matching layout page template structure rel element variation audience entry rels, or an empty list if no matches were found
	 */
	@Override
	public List<LayoutPageTemplateStructureRelElementVariationAudienceEntryRel>
		getLayoutPageTemplateStructureRelElementVariationAudienceEntryRelsByUuidAndCompanyId(
			String uuid, long companyId) {

		return layoutPageTemplateStructureRelElementVariationAudienceEntryRelPersistence.
			findByUuid_C(uuid, companyId);
	}

	/**
	 * Returns a range of layout page template structure rel element variation audience entry rels matching the UUID and company.
	 *
	 * @param uuid the UUID of the layout page template structure rel element variation audience entry rels
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of layout page template structure rel element variation audience entry rels
	 * @param end the upper bound of the range of layout page template structure rel element variation audience entry rels (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching layout page template structure rel element variation audience entry rels, or an empty list if no matches were found
	 */
	@Override
	public List<LayoutPageTemplateStructureRelElementVariationAudienceEntryRel>
		getLayoutPageTemplateStructureRelElementVariationAudienceEntryRelsByUuidAndCompanyId(
			String uuid, long companyId, int start, int end,
			OrderByComparator
				<LayoutPageTemplateStructureRelElementVariationAudienceEntryRel>
					orderByComparator) {

		return layoutPageTemplateStructureRelElementVariationAudienceEntryRelPersistence.
			findByUuid_C(uuid, companyId, start, end, orderByComparator);
	}

	/**
	 * Returns the layout page template structure rel element variation audience entry rel matching the UUID and group.
	 *
	 * @param uuid the layout page template structure rel element variation audience entry rel's UUID
	 * @param groupId the primary key of the group
	 * @return the matching layout page template structure rel element variation audience entry rel
	 * @throws PortalException if a matching layout page template structure rel element variation audience entry rel could not be found
	 */
	@Override
	public LayoutPageTemplateStructureRelElementVariationAudienceEntryRel
			getLayoutPageTemplateStructureRelElementVariationAudienceEntryRelByUuidAndGroupId(
				String uuid, long groupId)
		throws PortalException {

		return layoutPageTemplateStructureRelElementVariationAudienceEntryRelPersistence.
			findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the layout page template structure rel element variation audience entry rels.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.layout.page.template.model.impl.LayoutPageTemplateStructureRelElementVariationAudienceEntryRelModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of layout page template structure rel element variation audience entry rels
	 * @param end the upper bound of the range of layout page template structure rel element variation audience entry rels (not inclusive)
	 * @return the range of layout page template structure rel element variation audience entry rels
	 */
	@Override
	public List<LayoutPageTemplateStructureRelElementVariationAudienceEntryRel>
		getLayoutPageTemplateStructureRelElementVariationAudienceEntryRels(
			int start, int end) {

		return layoutPageTemplateStructureRelElementVariationAudienceEntryRelPersistence.
			findAll(start, end);
	}

	/**
	 * Returns the number of layout page template structure rel element variation audience entry rels.
	 *
	 * @return the number of layout page template structure rel element variation audience entry rels
	 */
	@Override
	public int
		getLayoutPageTemplateStructureRelElementVariationAudienceEntryRelsCount() {

		return layoutPageTemplateStructureRelElementVariationAudienceEntryRelPersistence.
			countAll();
	}

	/**
	 * Updates the layout page template structure rel element variation audience entry rel in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect LayoutPageTemplateStructureRelElementVariationAudienceEntryRelLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param layoutPageTemplateStructureRelElementVariationAudienceEntryRel the layout page template structure rel element variation audience entry rel
	 * @return the layout page template structure rel element variation audience entry rel that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public LayoutPageTemplateStructureRelElementVariationAudienceEntryRel
		updateLayoutPageTemplateStructureRelElementVariationAudienceEntryRel(
			LayoutPageTemplateStructureRelElementVariationAudienceEntryRel
				layoutPageTemplateStructureRelElementVariationAudienceEntryRel) {

		return layoutPageTemplateStructureRelElementVariationAudienceEntryRelPersistence.
			update(
				layoutPageTemplateStructureRelElementVariationAudienceEntryRel);
	}

	@Deactivate
	protected void deactivate() {
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			LayoutPageTemplateStructureRelElementVariationAudienceEntryRelLocalService.class,
			IdentifiableOSGiService.class, CTService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		layoutPageTemplateStructureRelElementVariationAudienceEntryRelLocalService =
			(LayoutPageTemplateStructureRelElementVariationAudienceEntryRelLocalService)
				aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return LayoutPageTemplateStructureRelElementVariationAudienceEntryRelLocalService.class.
			getName();
	}

	@Override
	public CTPersistence
		<LayoutPageTemplateStructureRelElementVariationAudienceEntryRel>
			getCTPersistence() {

		return layoutPageTemplateStructureRelElementVariationAudienceEntryRelPersistence;
	}

	@Override
	public Class<LayoutPageTemplateStructureRelElementVariationAudienceEntryRel>
		getModelClass() {

		return LayoutPageTemplateStructureRelElementVariationAudienceEntryRel.
			class;
	}

	@Override
	public <R, E extends Throwable> R updateWithUnsafeFunction(
			UnsafeFunction
				<CTPersistence
					<LayoutPageTemplateStructureRelElementVariationAudienceEntryRel>,
				 R, E> updateUnsafeFunction)
		throws E {

		return updateUnsafeFunction.apply(
			layoutPageTemplateStructureRelElementVariationAudienceEntryRelPersistence);
	}

	protected String getModelClassName() {
		return LayoutPageTemplateStructureRelElementVariationAudienceEntryRel.
			class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		DataSource dataSource =
			layoutPageTemplateStructureRelElementVariationAudienceEntryRelPersistence.
				getDataSource();

		DB db = DBManagerUtil.getDB();

		Connection currentConnection = CurrentConnectionUtil.getConnection(
			dataSource);

		try {
			if (currentConnection != null) {
				db.runSQL(currentConnection, new String[] {sql});

				return;
			}

			try (Connection connection = dataSource.getConnection()) {
				db.runSQL(connection, new String[] {sql});
			}
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	protected
		LayoutPageTemplateStructureRelElementVariationAudienceEntryRelLocalService
			layoutPageTemplateStructureRelElementVariationAudienceEntryRelLocalService;

	@Reference
	protected
		LayoutPageTemplateStructureRelElementVariationAudienceEntryRelPersistence
			layoutPageTemplateStructureRelElementVariationAudienceEntryRelPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		LayoutPageTemplateStructureRelElementVariationAudienceEntryRelLocalServiceBaseImpl.class);

}
// LIFERAY-SERVICE-BUILDER-HASH:-1049488260