liferay.home=/opt/liferay
company.default.web.id=liferay.com
company.default.locale=en_US
company.default.time.zone=UTC
default.admin.email.address.prefix=test
setup.wizard.enabled=false
admin.email.from.name=Test Test
admin.email.from.address=test@liferay.com