/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.tools.service.builder.test.model.impl;

import com.liferay.portal.tools.service.builder.test.model.CacheReplicatorEntry;
import com.liferay.portal.tools.service.builder.test.service.CacheReplicatorEntryLocalServiceUtil;

/**
 * The extended model base implementation for the CacheReplicatorEntry service. Represents a row in the &quot;CacheReplicatorEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CacheReplicatorEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CacheReplicatorEntryImpl
 * @see CacheReplicatorEntry
 * @generated
 */
public abstract class CacheReplicatorEntryBaseImpl
	extends CacheReplicatorEntryModelImpl implements CacheReplicatorEntry {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a cache replicator entry model instance should use the <code>CacheReplicatorEntry</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			CacheReplicatorEntryLocalServiceUtil.addCacheReplicatorEntry(this);
		}
		else {
			CacheReplicatorEntryLocalServiceUtil.updateCacheReplicatorEntry(
				this);
		}
	}

}
// LIFERAY-SERVICE-BUILDER-HASH:369653948