resource "aws_iam_role" "ack_prometheusservice" {
	assume_role_policy=jsonencode(
		{
			Statement=[
				{
					Action="sts:AssumeRoleWithWebIdentity"
					Condition={
						StringEquals={
							"${local.oidc_provider}:aud"="sts.amazonaws.com",
							"${local.oidc_provider}:sub"="system:serviceaccount:${var.ack_namespace}:ack-prometheusservice-controller"
						}
					}
					Effect="Allow"
					Principal={
						Federated="arn:aws:iam::${local.account_id}:oidc-provider/${local.oidc_provider}"
					}
				},
			]
			Version="2012-10-17"
		})
	count=var.observability_config.enabled ? 1 : 0
	name="${local.cluster_name}-ack-prometheusservice-irsa"
}
resource "aws_iam_role_policy" "ack_prometheusservice_amp_rules" {
	count=var.observability_config.enabled ? 1 : 0
	name="${local.cluster_name}-ack-prometheusservice-amp-rules-policy"
	policy=jsonencode(
		{
			Statement=[
				{
					Action=[
						"aps:CreateRuleGroupsNamespace",
						"aps:DeleteRuleGroupsNamespace",
						"aps:DescribeRuleGroupsNamespace",
						"aps:ListRuleGroupsNamespaces",
						"aps:ListTagsForResource",
						"aps:PutRuleGroupsNamespace",
						"aps:TagResource",
						"aps:UntagResource"
					],
					Effect="Allow",
					Resource=[
						"arn:aws:aps:${var.region}:${local.account_id}:rulegroupsnamespace/*",
						"arn:aws:aps:${var.region}:${local.account_id}:workspace/*"
					]
				}
			]
			Version="2012-10-17"
		})
	role=aws_iam_role.ack_prometheusservice[0].id
}
resource "helm_release" "ack_prometheusservice" {
	chart="prometheusservice-chart"
	count=var.observability_config.enabled ? 1 : 0
	create_namespace=true
	name="ack-prometheusservice"
	namespace=var.ack_namespace
	repository="oci://public.ecr.aws/aws-controllers-k8s"
	values=[
		yamlencode(
			{
				aws={
					region=var.region
				}
				serviceAccount={
					annotations={
						"eks.amazonaws.com/role-arn"=aws_iam_role.ack_prometheusservice[0].arn
					}
				}
			}),
	]
	version=var.ack_prometheusservice_helm_chart_version
}
