resource "helm_release" "external_secrets" {
	chart="external-secrets"
	create_namespace=true
	name="external-secrets"
	namespace=var.external_secrets_namespace
	repository="https://charts.external-secrets.io"
	values=[
		yamlencode(
			{
				certController={
					resources={
						limits={
							memory="512Mi"
						}
						requests={
							cpu="15m"
							memory="128Mi"
						}
					}
				}
				installCRDs=true
				resources={
					limits={
						memory="512Mi"
					}
					requests={
						cpu="15m"
						memory="128Mi"
					}
				}
				webhook={
					resources={
						limits={
							memory="256Mi"
						}
						requests={
							cpu="15m"
							memory="128Mi"
						}
					}
				}
			}),
	]
	version="1.0.0"
	wait=true
}
resource "kubernetes_labels" "external_secrets_namespace" {
	api_version="v1"
	kind="Namespace"
	metadata {
		name=var.external_secrets_namespace
	}
	labels=local.goldilocks_labels
}