resource "helm_release" "vpa" {
	chart="vpa"
	create_namespace=true
	name="vpa"
	namespace=var.vpa_namespace
	repository="https://charts.fairwinds.com/stable"
	values=[
		yamlencode(
			{
				rbac={
					create=true
				}
				recommender={
					enabled=true
					extraArgs={
						"kube-api-qps"="100"
						"kube-api-burst"="150"
					}
					resources={
						limits={
							cpu="200m"
							memory="512Mi"
						}
						requests={
							cpu="100m"
							memory="256Mi"
						}
					}
				}
				admissionController={
					enabled=false
				}
				updater={
					enabled=false
				}
			})
	]
	version="4.10.2"
}
