{{- if eq .Values.grafana.admin.existingSecret "grafana-admin-credentials" -}}
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
    labels:
        {{- include "observability.labels" . | nindent 8 }}
    name: grafana-admin-credentials
    namespace: {{ include "observability.namespace" . | quote }}
spec:
    allowRepeat: true
    digits: 8
    length: 32
    noUpper: false
    symbols: 0
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    labels:
        {{- include "observability.labels" . | nindent 8 }}
    name: grafana-admin-credentials
    namespace: {{ include "observability.namespace" . | quote }}
spec:
    dataFrom:
        -   sourceRef:
                generatorRef:
                    apiVersion: generators.external-secrets.io/v1alpha1
                    kind: Password
                    name: grafana-admin-credentials
    refreshInterval: "0"
    target:
        name: grafana-admin-credentials
        template:
            data:
                admin-password: "{{ `{{ .password }}` }}"
                admin-user: admin
            engineVersion: v2
{{- end -}}