/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

import fs from 'fs';
import {createRequire} from 'module';
import path from 'path';
import {PurgeCSS} from 'purgecss';

const require = createRequire(import.meta.url);

const outDir = path.resolve('src/assets');
const outFile = path.join(outDir, 'atlas.css');

let atlasPath;

try {
	atlasPath = require.resolve('@clayui/css/lib/css/atlas.css');
}
catch (error) {

	// eslint-disable-next-line no-console
	console.warn(
		'Atlas not resolvable; keeping the committed src/assets/atlas.css'
	);

	process.exit(0);
}

const clayDir = path.join(
	atlasPath.split(`${path.sep}@clayui${path.sep}`)[0],
	'@clayui'
);

const [purged] = await new PurgeCSS().purge({
	content: [
		'src/**/*.{ts,tsx}',
		'index.html',
		`${clayDir}/**/lib/**/*.{js,mjs}`,
	],
	css: [{extension: 'css', raw: fs.readFileSync(atlasPath, 'utf8')}],
	fontFace: false,
	keyframes: false,
	safelist: {
		greedy: [/lexicon-icon/, /^btn-/],
		standard: [
			/^:root$/,
			/^:host$/,
			'a',
			'body',
			'button',
			'div',
			'form',
			'h1',
			'h2',
			'h3',
			'html',
			'input',
			'label',
			'li',
			'p',
			'select',
			'span',
			'svg',
			'textarea',
			'ul',
			'use',
		],
	},
	variables: false,
});

fs.mkdirSync(outDir, {recursive: true});

fs.writeFileSync(
	outFile,
	`/* @generated by scripts/buildAtlas.mjs */\n${purged.css}`
);

// eslint-disable-next-line no-console
console.log(
	`Wrote purged Atlas (${purged.css.length} bytes) to ${path.relative(
		process.cwd(),
		outFile
	)}`
);
